/* The following code was generated by JFlex 1.6.1 */

package com.github.esrrhs.fakescript;

import com.github.esrrhs.fakescript.syntree.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>jflex.flex</tt>
 */
class Yylex implements YYParser.Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\2\1\0\1\0\1\1\22\0\1\0\1\50\1\5"+
    "\2\0\1\40\1\0\1\57\1\51\1\52\1\44\1\42\1\41\1\3"+
    "\1\35\1\43\12\34\1\45\1\0\1\47\1\46\1\36\2\0\4\33"+
    "\1\37\25\33\1\53\1\4\1\54\1\0\1\33\1\0\1\7\1\15"+
    "\1\20\1\27\1\11\1\17\1\31\1\22\1\23\1\33\1\16\1\24"+
    "\1\33\1\14\1\25\1\30\1\33\1\10\1\26\1\12\1\13\1\6"+
    "\1\21\1\33\1\32\1\33\1\55\1\0\1\56\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\21\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\1\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\1\1\26\1\27\1\5\1\30\1\31\1\0\1\4"+
    "\1\0\20\4\1\32\1\33\1\34\6\4\1\35\1\0"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\2\27\1\0\1\61\1\62\1\63"+
    "\1\4\1\64\4\4\1\65\4\4\1\66\12\4\1\67"+
    "\1\70\1\4\1\71\1\72\1\73\1\74\1\4\1\75"+
    "\1\4\1\76\1\77\12\4\1\0\2\4\1\100\1\101"+
    "\1\4\1\102\1\103\3\4\1\104\2\4\1\105\1\0"+
    "\1\67\1\106\1\107\2\4\1\110\1\111\3\4\1\112"+
    "\1\113\1\114\1\115";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\140\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420"+
    "\0\u0450\0\u0480\0\u04b0\0\140\0\u04e0\0\u0510\0\u0540\0\u0570"+
    "\0\u05a0\0\u05d0\0\u0600\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\u0630\0\u0660\0\140\0\u0690\0\u06c0\0\140\0\140"+
    "\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840"+
    "\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0"+
    "\0\u09f0\0\u0a20\0\u0a50\0\u01e0\0\u01e0\0\u01e0\0\u0a80\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\140\0\u0ba0\0\140\0\140"+
    "\0\140\0\140\0\140\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\140\0\140\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\u0bd0\0\140\0\u0c00\0\u01e0\0\u0c30\0\u01e0\0\u0c60"+
    "\0\u01e0\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u01e0\0\u0d50\0\u0d80"+
    "\0\u0db0\0\u0de0\0\u01e0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0"+
    "\0\u0f00\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020\0\u1050"+
    "\0\u1080\0\u01e0\0\u01e0\0\u01e0\0\u10b0\0\u01e0\0\u10e0\0\u01e0"+
    "\0\u01e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u1230"+
    "\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\u01e0\0\u01e0"+
    "\0\u1380\0\u01e0\0\u01e0\0\u13b0\0\u13e0\0\u1410\0\u01e0\0\u1440"+
    "\0\u1470\0\u01e0\0\u14a0\0\u14a0\0\u01e0\0\u01e0\0\u14d0\0\u1500"+
    "\0\u01e0\0\u01e0\0\u1530\0\u1560\0\u1590\0\u01e0\0\u01e0\0\u01e0"+
    "\0\u01e0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\14\1\17"+
    "\1\20\1\21\1\14\1\22\1\14\1\23\1\24\1\25"+
    "\1\26\1\14\1\27\1\14\1\30\1\31\1\32\1\14"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\3"+
    "\1\52\2\3\1\52\1\53\1\54\52\52\62\0\1\3"+
    "\60\0\1\55\30\0\1\56\1\0\1\57\7\0\1\60"+
    "\14\0\1\61\2\0\1\14\1\62\25\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\6\14\1\64\20\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\3\14\1\65\23\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\6\14\1\66"+
    "\7\14\1\67\10\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\2\14\1\70\11\14\1\71\12\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\27\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\5\14\1\72\11\14\1\73\7\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\2\14\1\74"+
    "\24\14\1\63\1\0\1\14\23\0\1\61\2\0\1\14"+
    "\1\75\3\14\1\76\11\14\1\77\7\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\1\14\1\100\15\14\1\101"+
    "\7\14\1\63\1\0\1\14\23\0\1\61\2\0\14\14"+
    "\1\102\12\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\6\14\1\103\2\14\1\104\6\14\1\105\6\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\2\14\1\106\24\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\4\14\1\107"+
    "\6\14\1\110\2\14\1\111\10\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\3\14\1\112\23\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\1\14\1\113\25\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\15\14\1\114\11\14"+
    "\1\63\1\0\1\14\33\0\1\115\20\0\1\30\1\116"+
    "\57\0\1\117\70\0\1\120\57\0\1\121\53\0\1\122"+
    "\3\0\1\123\57\0\1\124\57\0\1\125\57\0\1\126"+
    "\57\0\1\127\57\0\1\130\57\0\1\131\11\0\1\52"+
    "\2\0\1\52\2\0\52\52\4\0\1\132\1\133\2\0"+
    "\1\134\1\0\1\135\1\0\1\136\1\137\1\0\1\140"+
    "\37\0\1\141\1\55\1\142\1\143\55\55\34\0\1\56"+
    "\1\116\60\0\1\144\24\0\1\61\2\0\2\14\1\145"+
    "\24\14\1\63\1\0\1\14\26\0\26\146\3\0\1\146"+
    "\23\0\1\61\2\0\21\14\1\147\5\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\4\14\1\150\22\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\21\14\1\151\5\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\20\14\1\152"+
    "\6\14\1\63\1\0\1\14\23\0\1\61\2\0\5\14"+
    "\1\153\21\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\3\14\1\154\23\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\16\14\1\155\10\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\4\14\1\156\22\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\3\14\1\157\23\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\10\14\1\160\5\14\1\161"+
    "\10\14\1\63\1\0\1\14\23\0\1\61\2\0\6\14"+
    "\1\162\20\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\2\14\1\163\24\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\20\14\1\164\6\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\6\14\1\165\20\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\15\14\1\166\11\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\12\14\1\167\14\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\2\14\1\170\24\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\15\14\1\171"+
    "\11\14\1\63\1\0\1\14\23\0\1\61\2\0\3\14"+
    "\1\172\23\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\11\14\1\173\15\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\12\14\1\174\14\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\3\14\1\175\23\14\1\63\1\0\1\14"+
    "\54\0\1\176\25\0\1\143\63\0\26\177\3\0\1\177"+
    "\26\0\27\146\1\63\1\0\1\146\23\0\1\61\2\0"+
    "\5\14\1\200\21\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\3\14\1\201\23\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\3\14\1\202\23\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\6\14\1\203\20\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\16\14\1\204\10\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\1\14\1\205\25\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\3\14\1\206"+
    "\23\14\1\63\1\0\1\14\23\0\1\61\2\0\20\14"+
    "\1\207\6\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\12\14\1\210\14\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\3\14\1\211\23\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\4\14\1\212\13\14\1\213\6\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\16\14\1\214\10\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\16\14\1\215"+
    "\10\14\1\63\1\0\1\14\23\0\1\61\2\0\5\14"+
    "\1\216\21\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\4\14\1\217\22\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\3\14\1\220\23\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\1\14\1\221\25\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\10\14\1\222\16\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\16\14\1\223\10\14\1\63"+
    "\1\0\1\14\31\0\1\224\22\0\1\176\2\0\1\224"+
    "\23\0\1\61\2\0\27\177\2\0\1\177\23\0\1\61"+
    "\2\0\2\14\1\225\24\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\15\14\1\226\11\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\10\14\1\227\16\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\3\14\1\230\23\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\15\14\1\231\11\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\4\14\1\232"+
    "\22\14\1\63\1\0\1\14\23\0\1\61\2\0\3\14"+
    "\1\233\23\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\5\14\1\234\21\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\12\14\1\235\14\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\12\14\1\236\14\14\1\63\1\0\1\14"+
    "\23\0\1\61\2\0\22\14\1\237\4\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\5\14\1\240\21\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\1\14\1\241\25\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\21\14\1\242"+
    "\5\14\1\63\1\0\1\14\23\0\1\243\30\0\1\244"+
    "\26\0\1\61\2\0\6\14\1\245\20\14\1\63\1\0"+
    "\1\14\23\0\1\61\2\0\11\14\1\246\15\14\1\63"+
    "\1\0\1\14\23\0\1\61\2\0\6\14\1\247\20\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\21\14\1\250"+
    "\5\14\1\63\1\0\1\14\23\0\1\61\2\0\4\14"+
    "\1\251\22\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\14\14\1\252\12\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\16\14\1\253\10\14\1\63\1\0\1\14\23\0"+
    "\1\61\2\0\23\14\1\254\3\14\1\63\1\0\1\14"+
    "\54\0\1\244\26\0\1\61\2\0\5\14\1\255\21\14"+
    "\1\63\1\0\1\14\23\0\1\61\2\0\3\14\1\256"+
    "\23\14\1\63\1\0\1\14\23\0\1\61\2\0\4\14"+
    "\1\257\22\14\1\63\1\0\1\14\23\0\1\61\2\0"+
    "\3\14\1\260\23\14\1\63\1\0\1\14\23\0\1\61"+
    "\2\0\3\14\1\261\23\14\1\63\1\0\1\14\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5568];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\25\1\1\11\7\1\6\11"+
    "\2\1\1\11\2\1\2\11\1\0\1\1\1\0\31\1"+
    "\1\11\1\0\23\11\1\1\1\11\1\0\57\1\1\0"+
    "\16\1\1\0\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  fake m_f;
  StringBuilder string = new StringBuilder();
  /* store a reference to the YYParser object */
  private YYParser yyparser;
  
  private ParserVal yylval;
  
  private mybison m_mybison;
  
  public fake get_fake()
  {
	return m_f;
  }
  
  public void set_fake(fake f)
  {
	m_f = f;
  }
  
  public void set_mybison(mybison mb)
  {
	m_mybison = mb;
  }
  
  public mybison get_mybison()
  {
	return m_mybison;
  }
  
  public <T> T new_node(Class<? extends syntree_node> c, int lineno)
  {
	try
	{
		syntree_node t = null;
		t = c.newInstance();
		t.m_lno = lineno;
		return (T) t;
	}
	catch (Exception e)
	{
	  return null;
	}
  }

  public int get_line()
  {
	return yyline;
  }

  public Object getLVal() 
  {
    return yylval;
  }

  public void yyerror(String s)
  {
	m_mybison.lexer_error(s, yyline, yytext());
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the ja.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

      /* not supposed to occur according to specification of ja.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return YYParser.EOF;
            }
            case 178: break;
            default:
              {
                return YYParser.EOF;
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 78: break;
          case 2: 
            { return YYParser.MINUS;
            }
          case 79: break;
          case 3: 
            { yybegin(STRING); string.setLength(0);
            }
          case 80: break;
          case 4: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.IDENTIFIER;
            }
          case 81: break;
          case 5: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.NUMBER;
            }
          case 82: break;
          case 6: 
            { return YYParser.MORE;
            }
          case 83: break;
          case 7: 
            { return YYParser.DIVIDE_MOD;
            }
          case 84: break;
          case 8: 
            { return YYParser.ARG_SPLITTER;
            }
          case 85: break;
          case 9: 
            { return YYParser.PLUS;
            }
          case 86: break;
          case 10: 
            { return YYParser.DIVIDE;
            }
          case 87: break;
          case 11: 
            { return YYParser.MULTIPLY;
            }
          case 88: break;
          case 12: 
            { return YYParser.COLON;
            }
          case 89: break;
          case 13: 
            { return YYParser.ASSIGN;
            }
          case 90: break;
          case 14: 
            { return YYParser.LESS;
            }
          case 91: break;
          case 15: 
            { return YYParser.OPEN_BRACKET;
            }
          case 92: break;
          case 16: 
            { return YYParser.CLOSE_BRACKET;
            }
          case 93: break;
          case 17: 
            { return YYParser.OPEN_SQUARE_BRACKET;
            }
          case 94: break;
          case 18: 
            { return YYParser.CLOSE_SQUARE_BRACKET;
            }
          case 95: break;
          case 19: 
            { return YYParser.OPEN_BIG_BRACKET;
            }
          case 96: break;
          case 20: 
            { return YYParser.CLOSE_BIG_BRACKET;
            }
          case 97: break;
          case 21: 
            { string.append( yytext() );
            }
          case 98: break;
          case 22: 
            { yybegin(YYINITIAL); 
									yylval = new ParserVal(string.toString()); 
									yylval.ival = yyline + 1;
									return YYParser.STRING_DEFINITION;
            }
          case 99: break;
          case 23: 
            { /* ignore */
            }
          case 100: break;
          case 24: 
            { return YYParser.RIGHT_POINTER;
            }
          case 101: break;
          case 25: 
            { return YYParser.MINUS_ASSIGN;
            }
          case 102: break;
          case 26: 
            { return YYParser.IF;
            }
          case 103: break;
          case 27: 
            { return YYParser.IS;
            }
          case 104: break;
          case 28: 
            { return YYParser.OR;
            }
          case 105: break;
          case 29: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.FKUUID;
            }
          case 106: break;
          case 30: 
            { return YYParser.STRING_CAT;
            }
          case 107: break;
          case 31: 
            { return YYParser.MORE_OR_EQUAL;
            }
          case 108: break;
          case 32: 
            { return YYParser.DIVIDE_MOD_ASSIGN;
            }
          case 109: break;
          case 33: 
            { return YYParser.INC;
            }
          case 110: break;
          case 34: 
            { return YYParser.PLUS_ASSIGN;
            }
          case 111: break;
          case 35: 
            { return YYParser.DIVIDE_ASSIGN;
            }
          case 112: break;
          case 36: 
            { return YYParser.MULTIPLY_ASSIGN;
            }
          case 113: break;
          case 37: 
            { return YYParser.NEW_ASSIGN;
            }
          case 114: break;
          case 38: 
            { return YYParser.EQUAL;
            }
          case 115: break;
          case 39: 
            { return YYParser.LESS_OR_EQUAL;
            }
          case 116: break;
          case 40: 
            { return YYParser.NOT_EQUAL;
            }
          case 117: break;
          case 41: 
            { string.append( '\\' );
            }
          case 118: break;
          case 42: 
            { string.append( '\"' );
            }
          case 119: break;
          case 43: 
            { string.append( '\r' );
            }
          case 120: break;
          case 44: 
            { string.append( '\t' );
            }
          case 121: break;
          case 45: 
            { string.append( '\n' );
            }
          case 122: break;
          case 46: 
            { string.append( '\b' );
            }
          case 123: break;
          case 47: 
            { string.append( '\f' );
            }
          case 124: break;
          case 48: 
            { string.append( '\'' );
            }
          case 125: break;
          case 49: 
            { return YYParser.VAR_BEGIN;
            }
          case 126: break;
          case 50: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.IDENTIFIER_DOT;
            }
          case 127: break;
          case 51: 
            { return YYParser.AND;
            }
          case 128: break;
          case 52: 
            { return YYParser.END;
            }
          case 129: break;
          case 53: 
            { return YYParser.NOT;
            }
          case 130: break;
          case 54: 
            { return YYParser.FOR;
            }
          case 131: break;
          case 55: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.FKFLOAT;
            }
          case 132: break;
          case 56: 
            { yylval = new ParserVal(yytext());
	yylval.ival = yyline + 1;
	return YYParser.IDENTIFIER_POINTER;
            }
          case 133: break;
          case 57: 
            { return YYParser.ELSE;
            }
          case 134: break;
          case 58: 
            { return YYParser.FTRUE;
            }
          case 135: break;
          case 59: 
            { return YYParser.THEN;
            }
          case 136: break;
          case 60: 
            { return YYParser.NULL;
            }
          case 137: break;
          case 61: 
            { return YYParser.FAKE;
            }
          case 138: break;
          case 62: 
            { return YYParser.FUNC;
            }
          case 139: break;
          case 63: 
            { return YYParser.CASE;
            }
          case 140: break;
          case 64: 
            { return YYParser.BREAK;
            }
          case 141: break;
          case 65: 
            { return YYParser.FFALSE;
            }
          case 142: break;
          case 66: 
            { return YYParser.FCONST;
            }
          case 143: break;
          case 67: 
            { return YYParser.WHILE;
            }
          case 144: break;
          case 68: 
            { return YYParser.SLEEP;
            }
          case 145: break;
          case 69: 
            { return YYParser.YIELD;
            }
          case 146: break;
          case 70: 
            { return YYParser.RETURN;
            }
          case 147: break;
          case 71: 
            { return YYParser.ELSEIF;
            }
          case 148: break;
          case 72: 
            { return YYParser.STRUCT;
            }
          case 149: break;
          case 73: 
            { return YYParser.SWITCH;
            }
          case 150: break;
          case 74: 
            { return YYParser.INCLUDE;
            }
          case 151: break;
          case 75: 
            { return YYParser.DEFAULT;
            }
          case 152: break;
          case 76: 
            { return YYParser.PACKAGE;
            }
          case 153: break;
          case 77: 
            { return YYParser.CONTINUE;
            }
          case 154: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
